#!/bin/sh

git submodule add https://github.com/tpope/vim-pathogen.git bundle/vim-pathogen
git submodule add http://github.com/tpope/vim-fugitive.git bundle/vim-fugitive
git submodule add https://github.com/msanders/snipmate.vim.git bundle/snipmate.vim
git submodule add https://github.com/tpope/vim-surround.git bundle/vim-surround
git submodule add https://github.com/tpope/vim-git.git bundle/vim-git
git submodule add https://github.com/ervandew/supertab.git bundle/supertab
git submodule add https://github.com/fholgado/minibufexpl.vim.git bundle/minibufexpl
git submodule add https://github.com/wincent/Command-T.git bundle/Command-T
git submodule add https://github.com/mitechie/pyflakes-pathogen.git bundle/pyflakes-pathogen.git
git submodule add https://github.com/mileszs/ack.vim.git bundle/ack.vim
git submodule add https://github.com/sjl/gundo.vim.git bundle/gundo.vim
git submodule add https://github.com/fs111/pydoc.vim.git bundle/pydoc.vim
git submodule add https://github.com/vim-scripts/pep8.git bundle/pep8
git submodule add https://github.com/alfredodeza/pytest.vim.git bundle/pytest.vim
git submodule add https://github.com/reinh/vim-makegreen bundle/vim-makegreen
git submodule add https://github.com/vim-scripts/The-NERD-tree.git bundle/The-NERD-tree
git submodule add https://github.com/python-rope/ropevim.git bundle/ropevim
git submodule init
git submodule update
git submodule foreach git submodule init
git submodule foreach git submodule update
